/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'base': Defaults list is missing `_self_`. See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
[92mINFO [0m:      Starting Flower simulation, config: num_rounds=10, no round_timeout
model:
  _target_: torchvision.models.resnet18
  num_classes: ${foo}
strategy:
  _target_: flwr.server.strategy.FedAvg
  fraction_fit: 1.0e-05
  min_fit_clients: ${num_clients_per_round_fit}
  fraction_evaluate: 1.0e-05
  min_evaluate_clients: ${num_clients_per_round_eval}
  min_available_clients: ${num_clients}
  on_fit_config_fn:
    _target_: server.get_on_fit_config
    config: ${config_fit}
foo: 10
num_rounds: 10
num_clients: 100
batch_size: 20
num_classes: 10
num_clients_per_round_fit: 10
num_clients_per_round_eval: 25
config_fit:
  lr: 0.01
  momentum: 0.9
  local_epochs: 1

[2024-08-14 18:41:45,999][flwr][INFO] - Starting Flower simulation, config: num_rounds=10, no round_timeout
2024-08-14 18:41:48,581	INFO worker.py:1752 -- Started a local Ray instance.
[92mINFO [0m:      Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'node:128.232.115.66': 1.0, 'memory': 170294384436.0, 'object_store_memory': 77269021900.0, 'CPU': 56.0, 'GPU': 1.0, 'accelerator_type:G': 1.0}
[2024-08-14 18:41:54,685][flwr][INFO] - Flower VCE: Ray initialized with resources: {'node:__internal_head__': 1.0, 'node:128.232.115.66': 1.0, 'memory': 170294384436.0, 'object_store_memory': 77269021900.0, 'CPU': 56.0, 'GPU': 1.0, 'accelerator_type:G': 1.0}
[92mINFO [0m:      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-08-14 18:41:54,685][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[92mINFO [0m:      Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.0}
[2024-08-14 18:41:54,685][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.0}
[92mINFO [0m:      Flower VCE: Creating VirtualClientEngineActorPool with 28 actors
[2024-08-14 18:41:54,712][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 28 actors
[92mINFO [0m:      [INIT]
[2024-08-14 18:41:54,714][flwr][INFO] - [INIT]
[92mINFO [0m:      Requesting initial parameters from one random client
[2024-08-14 18:41:54,714][flwr][INFO] - Requesting initial parameters from one random client
[33m(raylet)[0m [2024-08-14 18:41:58,536 E 3756817 3756852] (raylet) file_system_monitor.cc:111: /tmp/ray/session_2024-08-14_18-41-46_134787_3756581 is over 95% full, available space: 13808898048; capacity: 2015100878848. Object creation will fail if spilling is required.
[36m(ClientAppActor pid=3760012)[0m [93mWARNING [0m:   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid: str">}. You can import the `Context` like this: `from flwr.common import Context`
[36m(ClientAppActor pid=3760012)[0m 
[36m(ClientAppActor pid=3760012)[0m             This is a deprecated feature. It will be removed
[36m(ClientAppActor pid=3760012)[0m             entirely in future versions of Flower.
[36m(ClientAppActor pid=3760012)[0m         
[92mINFO [0m:      Received initial parameters from one random client
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[36m(ClientAppActor pid=3760012)[0m tensor(0)
[36m(ClientAppActor pid=3760012)[0m [0]
[2024-08-14 18:42:02,211][flwr][INFO] - Received initial parameters from one random client
[2024-08-14 18:42:02,212][flwr][INFO] - Evaluating initial global parameters
[92mINFO [0m:      Evaluating initial global parameters
[91mERROR [0m:     Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead
[2024-08-14 18:42:03,788][flwr][ERROR] - Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead
[91mERROR [0m:     Traceback (most recent call last):
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/simulation/app.py", line 339, in start_simulation
    hist = run_fl(
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/server/server.py", line 490, in run_fl
    hist, elapsed_time = server.fit(
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/server/server.py", line 95, in fit
    res = self.strategy.evaluate(0, parameters=self.parameters)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/server/strategy/fedavg.py", line 167, in evaluate
    eval_res = self.evaluate_fn(server_round, parameters_ndarrays, {})
  File "/nfs-share/pa511/resnet/server.py", line 37, in evaluate_fn
    loss, accuracy = test(model, testloader, device)
  File "/nfs-share/pa511/resnet/model.py", line 50, in test
    outputs = net(images)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfs-share/pa511/resnet/pytorch_cifar/models/resnet.py", line 96, in forward
    out = F.relu(self.bn1(self.conv1(x)))
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead

[2024-08-14 18:42:03,797][flwr][ERROR] - Traceback (most recent call last):
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/simulation/app.py", line 339, in start_simulation
    hist = run_fl(
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/server/server.py", line 490, in run_fl
    hist, elapsed_time = server.fit(
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/server/server.py", line 95, in fit
    res = self.strategy.evaluate(0, parameters=self.parameters)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/server/strategy/fedavg.py", line 167, in evaluate
    eval_res = self.evaluate_fn(server_round, parameters_ndarrays, {})
  File "/nfs-share/pa511/resnet/server.py", line 37, in evaluate_fn
    loss, accuracy = test(model, testloader, device)
  File "/nfs-share/pa511/resnet/model.py", line 50, in test
    outputs = net(images)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfs-share/pa511/resnet/pytorch_cifar/models/resnet.py", line 96, in forward
    out = F.relu(self.bn1(self.conv1(x)))
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead

[2024-08-14 18:42:03,797][flwr][ERROR] - Your simulation crashed :(. This could be because of several reasons. The most common are: 
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example: 
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 2, 'num_gpus': 0.0} is not enough for your run). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 2, 'num_gpus': 0.0}.
Take a look at the Flower simulation examples for guidance <https://flower.ai/docs/framework/how-to-run-simulations.html>.
[91mERROR [0m:     Your simulation crashed :(. This could be because of several reasons. The most common are: 
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example: 
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 2, 'num_gpus': 0.0} is not enough for your run). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 2, 'num_gpus': 0.0}.
Take a look at the Flower simulation examples for guidance <https://flower.ai/docs/framework/how-to-run-simulations.html>.
Error executing job with overrides: []
Traceback (most recent call last):
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/simulation/app.py", line 339, in start_simulation
    hist = run_fl(
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/server/server.py", line 490, in run_fl
    hist, elapsed_time = server.fit(
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/server/server.py", line 95, in fit
    res = self.strategy.evaluate(0, parameters=self.parameters)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/server/strategy/fedavg.py", line 167, in evaluate
    eval_res = self.evaluate_fn(server_round, parameters_ndarrays, {})
  File "/nfs-share/pa511/resnet/server.py", line 37, in evaluate_fn
    loss, accuracy = test(model, testloader, device)
  File "/nfs-share/pa511/resnet/model.py", line 50, in test
    outputs = net(images)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfs-share/pa511/resnet/pytorch_cifar/models/resnet.py", line 96, in forward
    out = F.relu(self.bn1(self.conv1(x)))
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[128, 1, 28, 28] to have 3 channels, but got 1 channels instead

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 63, in main
    history = fl.simulation.start_simulation(
  File "/nfs-share/pa511/.cache/pypoetry/virtualenvs/advanced-pytorch-4G2CGpb3-py3.8/lib/python3.8/site-packages/flwr/simulation/app.py", line 375, in start_simulation
    raise RuntimeError("Simulation crashed.") from ex
RuntimeError: Simulation crashed.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
srun: error: ngongotaha: task 0: Exited with exit code 1
